### PR TITLE
Make the extension work with Webforms

### PR DESCRIPTION
**Pull request by robinmitra**
Payment fails when inserting the payment form into a Webform (using webform_civicrm Drupal module). This pull request fixes that, and includes a few other optimisations.

### CODE REVIEW

**Comment by drastik** [comment]
@robinmitra Nice work.

I _just_ fixed this myself, though quite differently.  That commit was coming today :) 
I will stash my work and give this a shot and go from there.  I think some merger of yours and mine will be the end result.
https://www.drupal.org/node/2225627#comment-9514049

**Comment by robinmitra** [comment]
@drastik Ah, didn't notice that thread! Let me know if I can be of any help.

**Comment by drastik** [comment]
Does yours still allow the webform to be submitted via `return` / `enter`?

I was thinking about disabling `keycode 13` (return) all together, that or I was going down a promising path of tracking which submit (button) is being used, to solve  the same issue you experienced, in Stripe's suggested  form.get(0).submit() -- which triggers the "Back" feature of webform.

**Comment by rgburton** [comment]
Well...I am glad to see this issue getting all this attention.  I just got a fix for this running on our test server yesterday.  At this point, I guess I'll just wait and see what comes from everyone's work and then see if mine adds anything additional.

I think the main difference in my civicrm_stripe.js update is that I preserved the submit handler and the form.get(0).submit() action by stashing the result of a submit button click in a hidden input field that is added to the form and gets posted when it is submitted.  I also added some code to handle switching between payment processors and to remove the name attribute from the credit card fields so they would not be posted to the server (this latter required a  modification to the webform_civicrm module to prevent validation errors).

One other issue that came up for me was the return page if stripe returns an error (e.g. card declined).  With webform submitting via the api there does not seem to be any civicrm page to redirect to.  I wind up at various pages  (anywhere from a civicrm admin form to the drupal home page) depending on permission levels.  I got around this problem by modifying the error handling in CRM/Core/Payment/Stripe.php so that it just returns an error object back to the calling routine if there is no civicrm form to redirect to.

**Comment by drastik** [comment]
@rgburton
Whip it out!  You have much more than either of ours. 
Can I persuade you to share your code?
I can merge this PR and start there, or we can see what yours looks like against 4.5-dev as it is now.

**Comment by rgburton** [comment]
@drastik
I'm working on it.  My patches are against a slightly older version of 4.5-dev.  I just pulled the current version and will update them.  Then I just need to get it all up to gitHub (I am new to using gitHub).

**Comment by robinmitra** [comment]
@rgburton Good stuff mate. In my case, Webform is gracefully handling card errors out of the box. It doesn't redirect anywhere and simply adds an error block near the top with the error message.

@drastik Mine doesn't allow submission via the `return` key yet. But I can image how that could be implemented. I'll whip something quick and see if it works.

**Comment by robinmitra** [comment]
@drastik Well, I ended up listening on `Enter` key press and firing a `click` event on the 'Submit' button. 

Ideally, I wanted to use the `submit` event to handle this, but even pressing the `Enter` key was firing the `click` event first on the 'Previous' button (in Chrome)! So, ended up simply firing the `click` event, which worked flawlessly.

**Comment by drastik** [comment]
@robinmitra 
I like the direction this is heading.

In mine, I kept the capture event under:
`$form.submit(function (event) {`
Rather than going to on click.  In this case `event` still contains if it was `return` (or `keycode 13`).
I need to get mine up here for you 2 to pick apart, I'll make another branch for it.

**Comment by rgburton** [comment]
@robinmitra

Nice fix for the enter key press.

Given your experience with the error handling, I decided to try the error handling again using the current 4.5-dev code without the changes I made.  It still does not work for me.  I wind up at the site home page and the only messages I get are complaints about qfKey and entryURL being undefined  indexes.  The generated url just ends with /?&_qf_Main_display=1&qfKey=.  That is not surprising since those keys are undefined.  Everything works fine for errors that get caught during generation of the token or by the webform validation routines.  But if the token gets submitted to stripe for payment and then gets rejected (e.g. a valid credit card where the charge is declined by the bank), this is the behavior I get.  That is what I am trying to fix with the changes I made to CRM/Core/Payment/Stripe.php.

I will also note that I made a small patch to the webform_civicrm module ( to submitPayment() in wf_crm_webform_postprocess.inc) in order to actually display the error message that stripe generates.

**Comment by drastik** [comment]
@rgburton 
That problem w/ the URL makes sense.  It only had CiviCRM (native) donation pages in mind.
I'm going to reference your PR from here:  #75

**Comment by drastik** [comment]
I think this was solved.

Reopen new issue if Webforms are still a problem.

**Pull request closed without merging**
