### PR TITLE
potential fix for #76

### PR DESCRIPTION
**Pull request by bjendres**
Potential "hotfix" for https://github.com/drastik/com.drastikbydesign.stripe/issues/76.
Someone would have to look over this, though. I have no idea what it was meant to do in the first place.

### CODE REVIEW

**Comment by drastik** [comment]
In the code's comment:
`// Handle multiple payment options and Stripe not being chosen.`

It was a another check in place to make sure Stripe doesn't get involved if there are multiple payment methods enabled on the site, and Stripe wasn't the actively chosen one.
Looks like 4.6 has changed some things on us and need to revisit our options.

**Comment by andrea-f** [comment]
Is there any news with this?

**Comment by bjendres** [comment]
No from our end, sorry. It worked for us. 

Follow #76 for current developments.

**Comment by andrea-f** [comment]
Yes thank you.

**Pull request closed without merging**
