### PR TITLE
Modify to stop error "Error: Stripe.js token was not passed! Report t…

### PR DESCRIPTION
**Pull request by mattwire**
Ref issues https://github.com/drastik/com.drastikbydesign.stripe/issues/76, https://github.com/drastik/com.drastikbydesign.stripe/issues/89

My installation: Drupal 7.39, Civicrm 4.6.8

### CODE REVIEW

**Comment by drastik** [comment]
That was there for discounts or free purchases that make the total $0.

**If your amount is not $0:  It is most likely the selector for amount has changed.**
This line:
https://github.com/mattwire/com.drastikbydesign.stripe/commit/2efdb49c2316bfd5e347e76843fde9defb63c8d6#diff-3318d8e04fc53f9807a26bd8ee752017L142

**If your amount is $0:**
It checks in stripe.php also if the amount is $0 to not worry about the token, etc and pass the contribution through.  If your installation is working with this patch, that means Stripe's backend API must have also been updated to allow $0 to pass through (previously a $0 charge attempt would send an error coming back from Stripe).
@mattwire Can you dump the vars before this line and see what `$params['amount']` you are getting with the failure?
https://github.com/drastik/com.drastikbydesign.stripe/blob/4.6-dev/CRM/Core/Payment/Stripe.php#L255

**Comment by mattwire** [comment]
Some notes:
1. The error only occurs when using the LIVE payment processor, not the test one.
2. It behaves exactly the same if pay later/other processor is enabled or not.

I believe the selector for amount has changed because it's returning true on line 143.

**Comment by mattwire** [comment]
I have just emailed you a full html dump of a page when it fails to the address listed on github.  The "total amount" was set to 12.00 when the check for amount returned 0.

**Comment by mattwire** [comment]
Anything else I can provide to assist with resolving this?

**Comment by drastik** [comment]
Have you tried with latest version after commits last week?

**Comment by mattwire** [comment]
The latest version didn't work.  But please see https://github.com/drastik/com.drastikbydesign.stripe/pull/102 for a fix.

**Pull request closed without merging**
