### PR TITLE
Error on recurring donations Received unknown parameter: name

### PR DESCRIPTION
**Pull request by jitendrapurohit**
Pretty new to this extension and getting myself familiar. I hit the same error as #248 and confirm that it is fixed by the changes made in this PR.

### CODE REVIEW

**Comment by danielstrum** [comment]
Yes, I can confirm also that this patch fixes the issue. Thanks!

**Comment by h-c-c** [comment]
Thanks @jitendrapurohit!  And thanks for testing @danielstrum!

**Comment by h-c-c** [comment]
I wonder if older api versions are tolerant of this?   If not, we should consider adding a new minimum version to the readme.

**Comment by MegaphoneJon** [comment]
IMO this issue is worth tagging a new release over.

**Pull request merged**
