### PR TITLE
refactoring to properly load stripe on submission error

### PR DESCRIPTION
**Pull request by jmcclelland**
See https://github.com/drastik/com.drastikbydesign.stripe/issues/76

### CODE REVIEW

**Comment by drastik** [comment]
Thanks, testing this.

**Comment by drastik** [comment]
I still get "Stripe.js token not passed!".
However, I like your new approach to gathering Stripe details.  I am merging this, then going further from here.

Thanks for this, nice work!

**Comment by jmcclelland** [comment]
Hm - still getting that error. I have found two reasons for getting the error:
- The civicrm-stripe.js file is not included on the page
- One of the exception is detected by the submit button event making the extension think it should return TRUE on submit without attaching the stripe data.

Can you tell which of these is the cause? (I've resorted to adding alert()'s throughout the code to tell the difference).

**Comment by drastik** [comment]
Yeah, this commit didn't fix the "Stripe.js not found" error.

I just committed a rather large update that solved it for me, and should for many others (hopefully all?).

Also, be sure your "Extension Resource URL" points to the relative path.
In Drupal:  /civicrm/admin/setting/url?reset=1
And your path would be like: `http://example.com/sites/all/civicrm_extensions/`
NOT full server path, like `/var/www/somewhere/then/here`.

**Comment by drastik** [comment]
The .js not found problem was from a small portion of `civicrm_stripe.js` where it was checking if the priceset amount was 0.  Somewhere along the line I merged a commit that broke that.

That file, and the Webhook.php are the new targets.  They are hideous to look at.

**Pull request merged**
