### PR TITLE
civicrm_payment_processor table missing payment_processor_type field

### PR DESCRIPTION
**Pull request by w3geekery**
Either need to use the civicrm_payment_processor.name field 
or left join to civicrm_payment_processor_type on civicrm_payment_processor.payment_processor_type_id = civicrm_payment_processor_type.id to get this to work.

### CODE REVIEW

**Comment by drastik** [comment]
Unless something has changed, the 'name' column is the customizable name you enter when adding the PayProc in Civi settings.  Meaning, we could not count on that for this purpose.  User can name it anything.

**Comment by w3geekery** [comment]
what about something like this instead?

```
$stripe_key = CRM_Core_DAO::singleValueQuery("SELECT user_name FROM civicrm_payment_processor cpp LEFT JOIN civicrm_payment_processor_type cppt ON cppt.id = cpp.payment_processor_type_id WHERE cppt.name = 'Stripe' AND is_test = '$test_mode'");
```

**Comment by caracolmzd** [comment]
I concur with @w3geekery the join to payment processor type is essential.
His patch would work.
A less verbose fix would be:
... FROM civicrm_payment_processor pp INNER JOIN civicrm_payment_processor_type ppt on pp.payment_processor_type_id = ppt.id AND ppt.name = 'Stripe"

This is a critical bug effecting recurring payments only.

**Comment by drastik** [comment]
I'd be glad to commit a new pull request that uses a JOIN to get the right name (not the user-supplied name).

Also not combining that require_once on the same line.

**Pull request closed without merging**
