### PR TITLE
Use setAppInfo function to set CiviCRM information

### PR DESCRIPTION
**Pull request by monishdeb**

### CODE REVIEW

**Comment by h-c-c** [comment]
Does this work for 4.6 also?  In spite of the branch name, we've been striving to support it. 

Thanks!

**Comment by monishdeb** [comment]
@h-c-c yes because the CRM functions used in the patch is present both in 4.6 and 4.7.

**Comment by monishdeb** [comment]
@h-c-c this patch was yesterday tested on civicrm.org and worked. Here's the ```Source``` info on charge log which now contain the CiviCRM tag, it's version and site name. 
dashboard copy

**Comment by h-c-c** [comment]
Ok, thanks for testing!

**Comment by monishdeb** [comment]
Thanks @h-c-c 😃

**Pull request merged**
