### PR TITLE
Customize webhook alert on enable to use UF relative path

### PR DESCRIPTION
**Pull request by EranSch**
This is a small enhancement but seems like a no-brainer. Rather than displaying the Drupal webhook path, why not use the constants established by Civi to customize the webhook alert so it's relative to not only the CMS but also the site's url? The result (in WordPress) looks like this:

webhook-alert

The default if the UF isn't found would be to still use `CIVICRM_UF_BASEURL` but just with the Drupal path. What I don't know is if we can rely on the constants always being available. Is there any instance where this wouldn't work?

Further, I think it would be prudent to list the webhook path elsewhere. It would seem as though the settings page for the payment processor would be a good location. What is the appropriate way to go about this? Include a template override in the plugin? I can revise this PR accordingly.

### CODE REVIEW

**Comment by drastik** [comment]
Love it.  Thanks!

**Comment by EranSch** [comment]
What do you think about including the webhook path in the 'Edit Payment Processor' view somewhere?

**Comment by drastik** [comment]
I like the idea.  Any pages that deal with config/settings for the payproc to have plenty of information about what/where/when/how they should be doing is great.

**Comment by EranSch** [comment]
Yeah... I think especially with the webhook path. It's easy to miss it in the notification popup and then difficult to find thereafter.

Would adding `templates/CRM/Admin/Form/PaymentProcessor.tpl` to the plugin be the reasonable way to do this or is there a better way?

**Comment by drastik** [comment]
I'd like to remain away from templates if possible.

I think in a form alter hook (like how it adds JS now) would be a good place.

**Comment by EranSch** [comment]
That sounds wise. Hmm... I'll have to educate myself a little more on that one then.

**Pull request merged**
