### PR TITLE
fix bad-query: payment_processor_type is not a char-field. add join to g...

### PR DESCRIPTION
**Pull request by caracolmzd**
...et ID.

### CODE REVIEW

**Comment by drastik** [comment]
Thanks!

Is civicrm_payment_processor_type.name the user-entered name for the payproc or the internally defined?

**Comment by caracolmzd** [comment]
I believe it is not. It is the name of the payment processor-type, not the name of the payment processor.

**Comment by universalhandle** [comment]
It's the name of the payment processor type, as defined [here](https://github.com/drastik/civicrm_stripe/blob/4.4-1.8/stripe.php#L189) and used in a query [here](https://github.com/drastik/civicrm_stripe/blob/4.4-1.8/stripe.php#L141-L147).

**Comment by drastik** [comment]
Thanks for the patch!!!

**Pull request merged**
