### PR TITLE
updated stripe to v2, make compatiable with webform_civicrm, code cleanu...

### PR DESCRIPTION
**Pull request by kurund**
...p / generalization to work with civicrm + webform, prevent sensitive data transfer across the server to ensure PCI compliance, also notice and indentation fixes

### CODE REVIEW

**Comment by kurund** [comment]
@drastik this also includes some fixes done by @aydun in https://github.com/drastik/civicrm_stripe/pull/55

**Comment by drastik** [comment]
Thanks Kurund!  Nice work.

**Comment by eliotlandrum** [comment]
Was pretty excited about this, but not able to get processing to work at all in 4.5 with this code (or the older code). Oddly, the only error I'm getting is one in the JavaScript console: "Uncaught TypeError: Cannot read property 'billingProfileIsHideable' of undefined ". The Confirm button does not initiate any visible action that I can see when I click it. I can start a new issue, but not sure what else to say.

**Comment by EranSch** [comment]
@eliotlandrum I was getting a similar problem a while back. It seemed as though Civi's JS API wasn't getting initialized properly. I had put somewhat of a hack together to resolve the `billingProfileIsHideable` error but later ended up not needing it. 

What CMS are you using?

What type of payment form are you getting this error on?

(I would suggest opening an issue too-- just to keep the topics separate. )

**Comment by eliotlandrum** [comment]
@Swingline0 I'm using Wordpress, and it's on a logged in Contribution page. From the comments, PR #64 might fix it. I need to setup a test system for it, as I lost my window for working on the live system.

**Comment by EranSch** [comment]
That would be wise. From my experience, we're still a ways from anything
that I would suggest using in production.

I suspect that we're one of few that are testing this extension in
WordPress. Let's be sure sure to share our findings!

**Pull request merged**
