### PR TITLE
Revised JS logic

### PR DESCRIPTION
**Pull request by EranSch**
Lets take time to make sure this change works for all use cases.

This PR addresses several things:
1. #60 - Form was not submitting due to non-specific selector
2. Assign `stripe-payment-form` class when building form in `stripe.php` rather than trying to target on document ready
3.  More caching of jQuery selectors for readability and performance
4.  Clear `onbeforeunload` which was triggering 'Are you sure you want to leave this page' dialog when form submits
5.  Remove `onclick` from submit button -- this was also proposed in #54.  
   By default, Civi adds the following to the submit button: `onclick="return submitOnce(this,'Main','Processing');"`  
   This was cause the form to submit before the `$.submit()` function could suppress it. Thus the stripeToken was created and the form would submit to Civi. This PR clears this attribute but recreates its functionality by disabling the button and changing its text where appropriate.

Thoughts?

### CODE REVIEW

**Comment by drastik** [comment]
Everything in here looks safe to me.

It's funny that there was an onbeforeunload attached.  I wonder if that was Civi, or was that a built-in browser thing (from Chrome, etc) since a form is on the page?

**Comment by EranSch** [comment]
The class approach seems to work in all the places I tested, including:
- Independent Contribution page
- Membership Signup
- Backend Credit Card registration

Regarding the onbeforeunload, I don't know where that came about but I assumed it was Civi. Perhaps the function invoked by the onclick unregistered it previously?

**Comment by kurund** [comment]
@Swingline0 @drastik I was working on similar cleanup and fixes for webform. But these changes looks good to me.. I can do my changes, once this is merged.

Actually I have submitted a revised PR: https://github.com/drastik/civicrm_stripe/pull/64

**Comment by drastik** [comment]
Wait, did these changes make it in with another pull?

**Comment by EranSch** [comment]
@drastik , Nope. The removal of the onclick attribute  had been proposed in a separate PR but never merged. I would suspect that this would now raise some conflicts. 

There are still some good aspects to this PR that I think would be beneficial. Particularly the programmatically added form class.

**Comment by EranSch** [comment]
I'll update this to be compatible with the last PR when I get some time.
Might be a day or two :)

**Comment by EranSch** [comment]
@drastik Okay, I got antsy. Take a look. This should include the best of both my and @kurund's latest contributions.

I've tested with a frontend contribution form and a backend credit card event registration. Both worked awesome. @kurund's #64 looks to have resolved #59 which is an added bonus!

**Comment by drastik** [comment]
I can confirm contributions working for me as well; however, I often did not have issues while others were having a miserable time.

**Comment by EranSch** [comment]
That seems to be a problem. With as many frameworks and implementations this payproc sees, it's not surprising there are so many varied experiences. 

One step at a time, I guess...

**Pull request merged**
