### PR TITLE
Fix sending receipt for recurring contributions

### PR DESCRIPTION
**Pull request by BorislavZlatanov**
Note: this is a work in progress. Please do not use in production yet. More testing and fixes are needed and will hopefully be done in the coming days.

Also please note the following two patches that are related to creating the PDF invoice/receipt:  
https://github.com/civicrm/civicrm-core/pull/6920
https://github.com/civicrm/civicrm-core/pull/6900

### CODE REVIEW

**Comment by BorislavZlatanov** [comment]
@drastik Just a note to let you know (so we don't duplicate the work) that I will be cleaning up the webhook.php file some more. If you are working on the extension, maybe you can fix #110 as you know Stripe's API.

**Comment by BorislavZlatanov** [comment]
My last commit fixes all issues I'm aware of in regards to the webhooks. Only thing that's remaining is to fix the fees and transaction ID issues mentioned in #110 . 

@drastik Again, sorry - I don't know why git is seeing the whole file as different rather than only the lines I changed. [Here is](https://www.diffchecker.com/n8d5uzqv) a comparison of before and after my changes for your convenience. Please let me know if you have any questions about the code.

**Comment by drastik** [comment]
I can't tell why on GitHub; will pull in CLI tomorrow and see if I can spot why the full-file change.

**Comment by BorislavZlatanov** [comment]
My last two commits fix the issues described in #110 . Note that in order for the fee to be set, you need to also apply this patch here: https://github.com/civicrm/civicrm-core/pull/7479

**Comment by drastik** [comment]
This PR has conflicts and does not allow me to merge.

Do you think you can create a new, clean PR with all of the changes you've introduced?  I will merge it in immediately.

**Comment by BorislavZlatanov** [comment]
I resolved the conflicts on this PR. Does this work for you?

**Pull request merged**
